### ISSUE TITLE
Error getting `"LC"` method to work in `testCov` 

### ISSUE THREAD

**Issue by geanders** [rickzhouwen/HDtest#10]
This may just be a problem in how I'm linking up the Fortran, but currently we get an error when we try to run `testCov` with the argument `method` set to `"LC"` (and also with it set to `"ALL"`: 

```r
testCov(GO54$X, GO54$Y, method = "LC", J = 100)
```
```
Error in .Fortran("code1", nr, A_mat, out = out, PACKAGE = "HDtest") : 
  "code1" not available for .Fortran() for package "HDtest"
```

Our Fortran code definitely includes a function called "code1", so I'm not sure yet why this error suggests it's not available. Other methods for `textCov` seem to work okay.

**Comment by geanders** [comment]
I've changed the examples for that function to use methods that don't give this error until we can figure out what's wrong. I'll change it back once we figure it out.

**Comment by rickzhouwen** [comment]
Perhaps, it has something to do with compile Fortran? .Fortran called a compiler first, is that the reason? I used it in R before (I called R in matlab, and then call Fortran in that "called R"... it works)

Let me know if it still report error, I will work with you together too

**Comment by geanders** [comment]
I think this is likely just in my build, as the package would not have made it on CRAN with an example that resulted in an error. However, until I figure out what this isn't working on my system, I've changed the example to something that does work, so I can get the build to work locally. We'll change it back once I figure it out. I'm only getting this problem, as far as I can tell so far, with one of the Fortran functions, not all of them.

**Comment by meca7653** [comment]
I got that Fortran error before. I think installing a Fortran complier will help.

**Comment by geanders** [comment]
I have gfortran installed. I am using version 4.8 when I build the package, and the package does build without error, which I think means that the Fortran code compiled, but then I'm getting the error when running a function that uses one of the Fortran functions. Which Fortran compiler and version worked successfully for you?

________________________________

**Comment by geanders** [comment]
So, everything works fine for me for the "LC" method when I either use the package directly from CRAN or install from source from the CRAN mirror on GitHub (which I think is compiling the Fortran code locally). I'll try to figure out if there's something I've changed in the source code in the `devel` branch that's breaking this in that branch.

**Comment by meca7653** [comment]
One more thing, did you change the package name? If so, code1 cannot find that.

**Comment by geanders** [comment]
I haven't changed the package name, but I am using a different branch (`devel`), so there's a chance it's something with that. 

I see that in the code that calls `code1` from the Fortran code, you have commented out: 

```
#dyn.load("one1.dll")
```

Is it necessary for me to created a shared library or something from the Fortran code?

**Comment by rickzhouwen** [comment]
In regular R, dyn.load("one1.dll") is needed so R will call that compiled Fortran code "one1.dll". Meng took care of that part before, maybe she has a better idea?

**Comment by geanders** [comment]
I figured out the problem on the `devel` branch--- I just had forgotten to add `useDynLib(HDtest)` to the NAMESPACE. There may be a way to automate so `roxygen2` adds that, but if not I'll make sure it's in there by hand.

**Comment by rickzhouwen** [comment]
Thanks a lot! Great!
