### ISSUE TITLE
Figure out a few details on DESCRIPTION

### ISSUE THREAD

**Issue by geanders** [rickzhouwen/HDtest#2]
I had a couple of questions for DESCRIPTION: 

- What is the email address for Tong He?
- How strongly do you feel about the Apache License? I feel like more of the R packages are under GPL-2, and I'm not sure if Apache is compatible with GPL-2. MIT is another choice that's more common for R packages that you may want to consider rather than Apache. 
- I added myself as an author. Is that okay?

**Comment by geanders** [comment]
Another question: 

If the package maintainer is a student, it may be better if we put a permanent email address for him, one that he would still have access to after he leaves CSU.

**Comment by rickzhouwen** [comment]
Thanks, Brooke:)

1. Tong He's email is hetongh@sfu.ca

2. I really do not know too much about Apache License. I think the reason it was put there is they copied some existing documentation as a convention. We can totally change it. 

3. Absolutely, you are definitely the author:)

4. I think the maintainer should be a faculty, the reason I put her there is that she uploaded it and we did not know if that has to be her. It is totally changeable

**Comment by geanders** [comment]
For 2: Yes, I would suggest that we change the license to GPL (>= 2). We will need to get the permission of all the package authors to make that change before we resubmit to CRAN.

For 4: I think it would be good for the student to be the maintainer while she is a student here, as it means a lot more on a CV to be a package maintainer, and if she did a lot of the initial coding work, it's an appropriate role. However, we will want to all talk to decide whether she wants to maintain that role after she leaves and, if not, one of us should take over then (and, if so, she will need to change her contact email then).

**Comment by rickzhouwen** [comment]
Great! Then, for 2, let's change it. What should I do? What type of permissions are needed?

For 4, that sounds great. I will ask her, and we can make decision together. In fact, I will email her with you cc'ed shortly.

**Comment by geanders** [comment]
For 2, I think just emailing the other authors to explain that we plan to change the license to GPL (>=2) (which, for reference, I think is the license R itself is under) and asking if we have their permission is fine.
