### ISSUE TITLE
Where is `var` defined for `twoMeans`?

### ISSUE THREAD

**Issue by geanders** [rickzhouwen/HDtest#9]
In the `twoMeans` function, there's a line that uses an object called `var`: 

```r
    Dk <- abs(rowMeans(X) - rowMeans(Y)) / sqrt(apply(X, 1, var) / n1 +
                                                  apply(Y, 1, var) / n2)
```

However, I didn't see where you defined `var` anywhere. It's not one of the inputs to the model, plus it's not defined earlier in this function. Where should this be defined? I think if a user made it into this branch of the if / else statement, they'd get an error for not having `var` defined.

**Comment by geanders** [comment]
Nevermind, figured this out. No problem.

**Comment by rickzhouwen** [comment]
:)
